on:
  push:
    tags:
      - 'v*'

name: Build & release gem
jobs:
  release:
    name: Build & release gem
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4
          bundler-cache: true
      - run: bundle exec bin/release-check
      - run: gem build lirc.gemspec
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
