---

name: Run tests
on:
  - push
  - pull_request

jobs:
  rspec:
    name: RSpec
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - ruby-2.5
          - ruby-2.6
          - ruby-2.7
        os:
          - macos-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rspec
  test-build:
    name: Test building the gem
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ruby:
          - ruby-2.5
          - ruby-2.6
          - ruby-2.7
        os:
          - macos-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec gem build lirc.gemspec
