on:
  - push
  - pull_request

name: Run tests
jobs:
  rspec:
    name: RSpec
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
    matrix: &ruby-matrix
      ruby:
        - ruby-2.4
        - ruby-2.5
        - ruby-2.6
        - ruby-2.7
        - ruby-3.0
      os:
        - macos-latest
        - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - &setup-ruby-with-matrix
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rspec spec/unit
  test-build:
    name: Test building the gem
    runs-on: ${{ matrix.os }}
    matrix: *test-matrix
    steps:
      - user: actions/checkout@v2
      - *setup-ruby-with-matrix
      - run: bundle exec gem build lirc.gem
