---

name: Run tests
on:
  - push
  - pull_request

jobs:
  rspec:
    name: RSpec
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # github actions doesn't support anchors yet, so this is duplicated in the action below too 🙃
      matrix:
        ruby:
          - ruby-2.6
          - ruby-2.7
          - ruby-3.0
          - ruby-3.1
          - ruby-3.2
        os:
          - macos-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rspec
  test-build:
    name: Test building the gem
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ruby:
          - ruby-2.6
          - ruby-2.7
          - ruby-3.0
          - ruby-3.1
          - ruby-3.2
        os:
          - macos-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec gem build lirc.gemspec
